name: storybook workflow

on:
  release:
    types: [created]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - run: yarn
#      - run: npm run linter:check
#      - run: yarn test

  deploy:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn deploy:storybook

  publish-npm:
#    needs: test
    env:
      REF: ${{github.ref}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn
      - run: npm run build:package
      - run: |
        ref='${{github.ref}}'
        npm version ${ref#refs/tags/}
      - run: npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
